In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import os
import sys
from pathlib import Path
import glob

project_root = Path.cwd().parent
sys.path.append(str(project_root))

import pandas as pd
import numpy as np

from src.load_data import load_confocal, load_confocal2

# Experimental conditions

In [2]:
silver_path = Path.cwd().parent / 'data/silver_layer/'

silver_confocal_path = Path.cwd().parent / 'data/silver_layer/confocal_runs_processed'
gold_profile_path = Path.cwd().parent / 'data/gold_layer/profile_pics_processed'

In [3]:

df_confocal = pd.read_pickle(silver_path / 'confocal_results_processed.pkl')
df_experimental = pd.read_pickle(silver_path / 'experimental_results.pkl')

In [4]:
missing_threshold = 50

In [5]:
df_consolidated = pd.merge(df_confocal, df_experimental[['run_id', 'jl', 'jg', 'date_identifier', 'pattern', 'reduced_pattern']], on='run_id', how='inner')

# Conditions evaluation

In [6]:
df_consolidated_2 = df_consolidated[df_confocal['t2_missing_percentage']<missing_threshold]

In [18]:
df_consolidated.query('reduced_pattern == "stratified"')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
37,38,0.983,0.984,0.002,0.0,0.646,0.623,0.247,99.9,0.000358,0.02,13.12,0306_02,stratified,stratified
38,39,0.984,0.985,0.002,24.8,1.091,0.670,1.473,69.9,0.000729,0.02,5.41,0306_03,stratified,stratified
47,48,0.983,0.985,0.004,0.0,0.949,0.703,0.914,54.3,0.000740,0.05,5.33,0312_07,stratified,stratified
48,49,0.983,0.985,0.003,0.0,0.834,0.585,1.111,50.7,0.000742,0.02,5.67,0312_08,stratified,stratified
104,105,0.982,0.985,0.005,74.4,0.826,0.628,0.803,98.9,0.009999,0.02,8.03,0322_04,stratified,stratified
107,108,0.983,0.985,0.004,0.0,0.791,0.583,0.650,92.6,0.010000,0.05,7.89,0322_07,stratified,stratified
146,147,0.984,0.985,0.003,90.1,1.124,0.658,1.388,99.5,0.011902,0.05,10.53,0325_v2_08,stratified,stratified

In [8]:
df_consolidated_2.groupby('reduced_pattern')['delta_time'].mean()

reduced_pattern
bubbly       0.000693
dispersed    0.010539
plug         0.005313
slug         0.001642
wavy         0.002071
Name: delta_time, dtype: float64

In [9]:
df_consolidated_2.query('reduced_pattern == "bubbly"')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
49,50,0.977,0.977,0.004,0.0,7.181,8.020,1.565,49.8,0.000694,2.00,0.26,0313_01,bubbly,bubbly
52,53,0.976,0.976,0.005,0.0,4.491,3.227,2.739,49.5,0.000691,1.99,0.80,0313_04,bubbly,bubbly
58,59,0.977,0.977,0.004,0.0,5.476,8.013,2.791,40.8,0.000720,1.48,0.52,0313_10,bubbly,bubbly
59,60,0.977,0.977,0.004,0.0,6.056,8.020,2.545,44.9,0.000718,1.48,0.39,0313_11,bubbly,bubbly
60,61,0.978,0.979,0.004,0.0,6.791,8.020,2.155,41.7,0.000714,1.48,0.26,0313_12,bubbly,bubbly
61,62,0.975,0.975,0.005,0.0,6.936,8.020,1.935,46.1,0.000720,1.47,0.27,0314_01,bubbly,bubbly
62,63,0.978,0.978,0.003,0.0,7.926,8.020,0.626,10.1,0.000657,0.96,0.26,0314_02,bubbly,bubbly
63,64,0.978,0.978,0.003,0.0,7.712,8.020,1.228,16.1,0.000658,0.97,0.39,0314_03,bubbly,bubbly
64,65,0.979,0.979,0.003,0.0,7.285,8.020,1.853,26.5,0.000666,0.97,0.52,0314_04,bubbly,bubbly

In [10]:
df_consolidated_2.query('reduced_pattern == "dispersed"')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
53,54,0.976,0.977,0.005,0.0,2.842,1.445,2.734,44.3,0.000683,1.98,1.29,0313_05,bubbly-churn,dispersed
54,55,0.976,0.976,0.005,0.0,3.655,1.927,2.960,38.7,0.000697,1.99,1.18,0313_06,bubbly-churn,dispersed
73,74,0.978,0.978,0.003,0.0,1.138,1.126,0.394,0.0,0.010000,1.97,2.10,0318_01,bubbly-churn,dispersed
74,75,0.979,0.978,0.004,0.0,1.149,1.141,0.407,0.0,0.010000,1.96,2.62,0318_02,bubbly-churn,dispersed
75,76,0.980,0.979,0.004,0.0,1.097,1.068,0.395,0.0,0.010000,1.99,4.06,0318_03,bubbly-churn,dispersed
76,77,0.980,0.980,0.004,0.0,1.056,1.002,0.407,0.0,0.010000,2.01,5.23,0318_04,bubbly-churn,dispersed
79,80,0.979,0.978,0.004,38.4,1.177,1.016,0.544,38.4,0.017825,1.49,3.93,0318_07,bubbly-churn,dispersed
80,81,0.979,0.978,0.004,47.8,1.237,1.037,0.582,47.9,0.017825,1.48,2.63,0318_08,bubbly-churn,dispersed
81,82,0.978,0.978,0.004,18.5,1.265,1.045,0.593,18.6,0.017825,1.50,2.09,0318_09,bubbly-churn,dispersed

In [15]:
df_consolidated_2.query('reduced_pattern == "plug"').query('run_id<66').sort_values('jl')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
34,35,0.980,0.980,0.005,0.0,1.597,0.805,1.981,43.1,0.000610,0.12,1.31,0305_08,plug,plug
33,34,0.980,0.979,0.005,0.0,2.157,0.594,3.067,37.2,0.000615,0.12,0.53,0305_07,plug,plug
35,36,0.978,0.978,0.005,0.0,1.703,0.548,2.614,30.4,0.000614,0.24,1.34,0305_09,plug,plug
32,33,0.977,0.977,0.005,0.0,2.915,0.676,3.415,23.3,0.000617,0.24,0.52,0305_06,plug,plug
31,32,0.976,0.976,0.004,0.0,3.521,1.165,3.466,25.5,0.000618,0.37,0.51,0305_05,plug,plug
30,31,0.975,0.975,0.004,0.0,3.950,1.471,3.478,27.4,0.000627,0.48,0.53,0305_04,plug,plug
28,29,0.975,0.975,0.003,0.0,5.238,8.020,3.301,37.3,0.000636,0.72,0.45,0305_02,plug,plug
27,28,0.976,0.976,0.004,0.0,5.117,8.020,3.370,33.1,0.000631,0.79,0.52,0305_01,plug,plug

In [14]:
df_consolidated_2.query('reduced_pattern == "plug"')['run_id'].unique()

array([ 28,  29,  31,  32,  33,  34,  35,  36,  66,  68,  69, 122, 123,
       126, 128, 130, 131, 132])

In [17]:
df_consolidated_2.query('reduced_pattern == "slug"').sort_values('jl')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
14,15,0.980,0.981,0.004,0.0,1.044,0.888,0.763,38.9,0.000731,0.49,3.33,0304_03,slug,slug
13,14,0.980,0.980,0.004,0.0,1.270,0.836,1.508,35.4,0.000735,0.61,2.79,0304_02,slug,slug
22,23,0.980,0.980,0.004,0.0,1.059,0.829,0.973,35.9,0.000732,0.61,3.44,0304_11,slug,slug
24,25,0.979,0.979,0.004,0.0,1.262,0.761,1.685,38.9,0.000749,0.86,2.66,0304_13,slug,slug
12,13,0.980,0.980,0.004,0.0,2.584,0.835,3.074,16.7,0.000730,0.88,1.50,0304_01,slug,slug
66,67,0.978,0.978,0.004,0.0,3.971,1.535,3.473,13.7,0.000665,0.97,1.30,0314_06,slug,slug
86,87,0.972,0.972,0.004,0.0,1.922,1.028,2.208,46.4,0.010000,1.05,2.06,0321_01,slug,slug
57,58,0.978,0.978,0.005,0.0,4.782,3.276,3.056,28.7,0.000693,1.48,0.80,0313_09,slug,slug
56,57,0.977,0.977,0.005,0.0,3.765,1.656,3.230,26.2,0.000694,1.49,1.17,0313_08,slug,slug
55,56,0.978,0.978,0.005,0.0,3.075,1.243,3.107,30.3,0.000694,1.50,1.31,0313_07,slug,slug

In [ ]:
67, 56, 58, 25

array([13, 14, 15, 23, 25, 56, 57, 58, 67, 87])

In [13]:
df_consolidated_2.query('reduced_pattern == "wavy"')

,run_id,t1_mean,t1_median,t1_std,t1_missing_percentage,t2_mean,t2_median,t2_std,t2_missing_percentage,delta_time,jl,jg,date_identifier,pattern,reduced_pattern
39,40,0.982,0.984,0.003,5.1,1.038,0.841,0.840,15.0,0.000743,0.03,2.79,0306_04,stratified-wavy,wavy
40,41,0.982,0.983,0.003,0.0,1.147,1.060,0.550,4.3,0.000745,0.07,2.71,0306_05,stratified-wavy,wavy
43,44,0.980,0.980,0.005,0.0,1.032,0.801,0.907,39.9,0.000762,0.29,5.38,0312_03,wavy,wavy
44,45,0.980,0.980,0.005,0.0,0.987,0.759,0.919,34.7,0.000755,0.20,5.33,0312_04,wavy,wavy
45,46,0.981,0.982,0.005,0.0,1.028,0.721,1.107,41.5,0.000749,0.15,5.44,0312_05,wavy,wavy
46,47,0.981,0.984,0.004,0.0,0.935,0.672,1.008,41.9,0.000743,0.10,5.26,0312_06,wavy,wavy
147,148,0.976,0.975,0.005,0.0,0.795,0.689,0.427,26.3,0.010000,0.05,4.00,0325_v2_09,stratified-wavy,wavy

In [ ]:
41, 45, 44